version: 2

sources:
  - name: adventureworks-erp
    schema: sap_adw
    description: This is the adventureworks erp postgres database replica
    tables:
      - name: address
      - name: countryregion
      - name: creditcard
      - name: customer
      - name: person
      - name: product
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesreason
      - name: stateprovince
      - name: store